name: Node.js CI

on:
  push:
    branches:
      - main  # O workflow será executado em pushes no branch principal
  pull_request:
    branches:
      - main  # Também será executado quando um pull request for feito para o branch principal

jobs:
  build:
    runs-on: ubuntu-latest  # O processo será executado em uma máquina virtual com Ubuntu

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Escolha a versão que seu projeto utiliza

    - name: Verificar diretório atual antes de instalar no cliente
      run: pwd  # Confirma em qual diretório estamos para garantir que estamos no lugar certo

    - name: Navegar até o diretório do cliente
      run: cd client && npm install  # Navega até o diretório 'client' e instala as dependências

    - name: Rodar os testes no cliente
      run: cd client && npm test  # Roda os testes no diretório 'client'

    - name: Verificar diretório atual antes de instalar no servidor
      run: pwd  # Confirma o diretório atual antes de rodar o servidor

    - name: Navegar até o diretório do servidor
      run: cd server && npm install  # Navega até o diretório 'server' e instala as dependências

    - name: Rodar os testes no servidor
      run: cd server && npm test  # Roda os testes no diretório 'server'
